// Code generated by ent, DO NOT EDIT.

package openaioauthaccountaccesspolicy

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the openaioauthaccountaccesspolicy type in the database.
	Label = "open_aio_auth_account_access_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldDefaultForNewUsers holds the string denoting the default_for_new_users field in the database.
	FieldDefaultForNewUsers = "default_for_new_users"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the openaioauthaccountaccesspolicy in the database.
	Table = "openai_oauth_account_access_policies"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "openai_oauth_account_access_policies"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for openaioauthaccountaccesspolicy fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldMode,
	FieldDefaultForNewUsers,
	FieldRevision,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDefaultForNewUsers holds the default value on creation for the "default_for_new_users" field.
	DefaultDefaultForNewUsers bool
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int64
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Mode defines the type for the "mode" enum field.
type Mode string

// ModePublic is the default value of the Mode enum.
const DefaultMode = ModePublic

// Mode values.
const (
	ModePublic     Mode = "public"
	ModeRestricted Mode = "restricted"
)

func (m Mode) String() string {
	return string(m)
}

// ModeValidator is a validator for the "mode" field enum values. It is called by the builders before save.
func ModeValidator(m Mode) error {
	switch m {
	case ModePublic, ModeRestricted:
		return nil
	default:
		return fmt.Errorf("openaioauthaccountaccesspolicy: invalid enum value for mode field: %q", m)
	}
}

// OrderOption defines the ordering options for the OpenAIOAuthAccountAccessPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByDefaultForNewUsers orders the results by the default_for_new_users field.
func ByDefaultForNewUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultForNewUsers, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
	)
}
