// Code generated by ent, DO NOT EDIT.

package openaioauthaccountaccesspolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldAccountID, v))
}

// DefaultForNewUsers applies equality check predicate on the "default_for_new_users" field. It's identical to DefaultForNewUsersEQ.
func DefaultForNewUsers(v bool) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldDefaultForNewUsers, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldRevision, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNotIn(FieldAccountID, vs...))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v Mode) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v Mode) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...Mode) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...Mode) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNotIn(FieldMode, vs...))
}

// DefaultForNewUsersEQ applies the EQ predicate on the "default_for_new_users" field.
func DefaultForNewUsersEQ(v bool) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldDefaultForNewUsers, v))
}

// DefaultForNewUsersNEQ applies the NEQ predicate on the "default_for_new_users" field.
func DefaultForNewUsersNEQ(v bool) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldDefaultForNewUsers, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int64) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLTE(FieldRevision, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIOAuthAccountAccessPolicy) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIOAuthAccountAccessPolicy) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIOAuthAccountAccessPolicy) predicate.OpenAIOAuthAccountAccessPolicy {
	return predicate.OpenAIOAuthAccountAccessPolicy(sql.NotPredicates(p))
}
