-- Store Prompt Audit chat evidence below the user/session hierarchy. Event rows
-- keep only detection metadata and references so repeated content can be shared
-- and chat data can be omitted from logical database backups.

ALTER TABLE prompt_audit_jobs
    ADD COLUMN IF NOT EXISTS session_key VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS session_source VARCHAR(32) NOT NULL DEFAULT '';

ALTER TABLE prompt_audit_events
    ADD COLUMN IF NOT EXISTS session_key VARCHAR(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS session_source VARCHAR(32) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS prompt_audit_sessions (
    id              BIGSERIAL PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_key     VARCHAR(64) NOT NULL,
    session_source  VARCHAR(32) NOT NULL DEFAULT '',
    first_seen_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prompt_audit_sessions_user_key UNIQUE (user_id, session_key)
);

CREATE TABLE IF NOT EXISTS prompt_audit_chat_records (
    id                    BIGSERIAL PRIMARY KEY,
    session_id            BIGINT NOT NULL REFERENCES prompt_audit_sessions(id) ON DELETE CASCADE,
    content_hash          VARCHAR(64) NOT NULL,
    full_prompt           TEXT NOT NULL DEFAULT '',
    full_prompt_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    context_ciphertext    TEXT,
    context_sha256        VARCHAR(64),
    context_bytes         BIGINT NOT NULL DEFAULT 0,
    segment_count         INTEGER NOT NULL DEFAULT 0,
    retention_until       TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_prompt_audit_chat_records_session_content UNIQUE (session_id, content_hash),
    CONSTRAINT chk_prompt_audit_chat_records_context_bytes CHECK (context_bytes >= 0),
    CONSTRAINT chk_prompt_audit_chat_records_segment_count CHECK (segment_count >= 0)
);

ALTER TABLE prompt_audit_events
    -- This is an application-managed reference. The chat table is omitted from
    -- backups, so a database restore must allow metadata events to retain a
    -- dangling content reference after the payload is intentionally absent.
    ADD COLUMN IF NOT EXISTS chat_record_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_prompt_audit_sessions_user_last_seen
    ON prompt_audit_sessions(user_id, last_seen_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_prompt_audit_chat_records_session_created
    ON prompt_audit_chat_records(session_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_prompt_audit_chat_records_retention
    ON prompt_audit_chat_records(retention_until, id);
CREATE INDEX IF NOT EXISTS idx_prompt_audit_events_chat_record
    ON prompt_audit_events(chat_record_id);

-- Historical rows had no session identity. Keep their evidence accessible by
-- assigning one opaque request-scoped session per event before clearing the old
-- in-row/context-table copies. md5 is sufficient for this migration-only key;
-- new rows use the SHA-256 key generated by the application.
UPDATE prompt_audit_events
SET session_key = md5('sub2api:legacy-prompt-audit-session:' || COALESCE(user_id::TEXT, '0') || ':' || id::TEXT)
WHERE session_key = '';

UPDATE prompt_audit_jobs j
SET session_key = e.session_key,
    session_source = 'legacy_event'
FROM prompt_audit_events e
WHERE e.job_id = j.id AND j.session_key = '';

INSERT INTO prompt_audit_sessions (user_id, session_key, session_source, first_seen_at, last_seen_at)
SELECT e.user_id, e.session_key, 'legacy_event', MIN(e.created_at), MAX(e.created_at)
FROM prompt_audit_events e
WHERE e.user_id IS NOT NULL AND e.session_key <> ''
GROUP BY e.user_id, e.session_key
ON CONFLICT (user_id, session_key) DO UPDATE SET
    first_seen_at = LEAST(prompt_audit_sessions.first_seen_at, EXCLUDED.first_seen_at),
    last_seen_at = GREATEST(prompt_audit_sessions.last_seen_at, EXCLUDED.last_seen_at);

INSERT INTO prompt_audit_chat_records (
    session_id, content_hash, full_prompt, full_prompt_truncated,
    context_ciphertext, context_sha256, context_bytes, segment_count, retention_until, created_at
)
SELECT s.id,
       md5('sub2api:legacy-prompt-audit-record:v1:' || e.id::TEXT),
       e.full_prompt,
       e.full_prompt_truncated,
       c.context_ciphertext,
       c.context_sha256,
       COALESCE(c.context_bytes, 0),
       COALESCE(c.segment_count, 0),
       NULL,
       e.created_at
FROM prompt_audit_events e
JOIN prompt_audit_sessions s ON s.user_id = e.user_id AND s.session_key = e.session_key
LEFT JOIN prompt_audit_event_contexts c ON c.event_id = e.id
WHERE e.full_prompt <> '' OR c.event_id IS NOT NULL
ON CONFLICT (session_id, content_hash) DO NOTHING;

UPDATE prompt_audit_events e
SET chat_record_id = r.id
FROM prompt_audit_sessions s, prompt_audit_chat_records r
WHERE s.user_id = e.user_id
  AND s.session_key = e.session_key
  AND r.session_id = s.id
  AND r.content_hash = md5('sub2api:legacy-prompt-audit-record:v1:' || e.id::TEXT);

-- The new chat table is the sole owner of historical complete content. Keep
-- the legacy table as an empty compatibility shell for rolling migrations.
UPDATE prompt_audit_events SET full_prompt = '';
DELETE FROM prompt_audit_event_contexts;

COMMENT ON TABLE prompt_audit_sessions IS 'User-scoped opaque Prompt Audit sessions';
COMMENT ON TABLE prompt_audit_chat_records IS 'Prompt Audit chat evidence; excluded from logical backups and retained by policy';
