// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/account"
	"github.com/LuckyKuang/sub2api-plus/ent/openaioauthaccountaccesspolicy"
)

// OpenAIOAuthAccountAccessPolicyCreate is the builder for creating a OpenAIOAuthAccountAccessPolicy entity.
type OpenAIOAuthAccountAccessPolicyCreate struct {
	config
	mutation *OpenAIOAuthAccountAccessPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetAccountID(v int64) *OpenAIOAuthAccountAccessPolicyCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetMode(v openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetNillableMode(v *openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetDefaultForNewUsers sets the "default_for_new_users" field.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetDefaultForNewUsers(v bool) *OpenAIOAuthAccountAccessPolicyCreate {
	_c.mutation.SetDefaultForNewUsers(v)
	return _c
}

// SetNillableDefaultForNewUsers sets the "default_for_new_users" field if the given value is not nil.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetNillableDefaultForNewUsers(v *bool) *OpenAIOAuthAccountAccessPolicyCreate {
	if v != nil {
		_c.SetDefaultForNewUsers(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetRevision(v int64) *OpenAIOAuthAccountAccessPolicyCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetNillableRevision(v *int64) *OpenAIOAuthAccountAccessPolicyCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetCreatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetNillableCreatedAt(v *time.Time) *OpenAIOAuthAccountAccessPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetUpdatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetNillableUpdatedAt(v *time.Time) *OpenAIOAuthAccountAccessPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SetAccount(v *Account) *OpenAIOAuthAccountAccessPolicyCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the OpenAIOAuthAccountAccessPolicyMutation object of the builder.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) Mutation() *OpenAIOAuthAccountAccessPolicyMutation {
	return _c.mutation
}

// Save creates the OpenAIOAuthAccountAccessPolicy in the database.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) Save(ctx context.Context) (*OpenAIOAuthAccountAccessPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) SaveX(ctx context.Context) *OpenAIOAuthAccountAccessPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) defaults() {
	if _, ok := _c.mutation.Mode(); !ok {
		v := openaioauthaccountaccesspolicy.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.DefaultForNewUsers(); !ok {
		v := openaioauthaccountaccesspolicy.DefaultDefaultForNewUsers
		_c.mutation.SetDefaultForNewUsers(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := openaioauthaccountaccesspolicy.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := openaioauthaccountaccesspolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := openaioauthaccountaccesspolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OpenAIOAuthAccountAccessPolicyCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "OpenAIOAuthAccountAccessPolicy.account_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "OpenAIOAuthAccountAccessPolicy.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := openaioauthaccountaccesspolicy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthAccountAccessPolicy.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultForNewUsers(); !ok {
		return &ValidationError{Name: "default_for_new_users", err: errors.New(`ent: missing required field "OpenAIOAuthAccountAccessPolicy.default_for_new_users"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "OpenAIOAuthAccountAccessPolicy.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := openaioauthaccountaccesspolicy.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthAccountAccessPolicy.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpenAIOAuthAccountAccessPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpenAIOAuthAccountAccessPolicy.updated_at"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "OpenAIOAuthAccountAccessPolicy.account"`)}
	}
	return nil
}

func (_c *OpenAIOAuthAccountAccessPolicyCreate) sqlSave(ctx context.Context) (*OpenAIOAuthAccountAccessPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OpenAIOAuthAccountAccessPolicyCreate) createSpec() (*OpenAIOAuthAccountAccessPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &OpenAIOAuthAccountAccessPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(openaioauthaccountaccesspolicy.Table, sqlgraph.NewFieldSpec(openaioauthaccountaccesspolicy.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.DefaultForNewUsers(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldDefaultForNewUsers, field.TypeBool, value)
		_node.DefaultForNewUsers = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   openaioauthaccountaccesspolicy.AccountTable,
			Columns: []string{openaioauthaccountaccesspolicy.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthAccountAccessPolicyUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthAccountAccessPolicyCreate) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	_c.conflict = opts
	return &OpenAIOAuthAccountAccessPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthAccountAccessPolicyCreate) OnConflictColumns(columns ...string) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthAccountAccessPolicyUpsertOne{
		create: _c,
	}
}

type (
	// OpenAIOAuthAccountAccessPolicyUpsertOne is the builder for "upsert"-ing
	//  one OpenAIOAuthAccountAccessPolicy node.
	OpenAIOAuthAccountAccessPolicyUpsertOne struct {
		create *OpenAIOAuthAccountAccessPolicyCreate
	}

	// OpenAIOAuthAccountAccessPolicyUpsert is the "OnConflict" setter.
	OpenAIOAuthAccountAccessPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) SetAccountID(v int64) *OpenAIOAuthAccountAccessPolicyUpsert {
	u.Set(openaioauthaccountaccesspolicy.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) UpdateAccountID() *OpenAIOAuthAccountAccessPolicyUpsert {
	u.SetExcluded(openaioauthaccountaccesspolicy.FieldAccountID)
	return u
}

// SetMode sets the "mode" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) SetMode(v openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpsert {
	u.Set(openaioauthaccountaccesspolicy.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) UpdateMode() *OpenAIOAuthAccountAccessPolicyUpsert {
	u.SetExcluded(openaioauthaccountaccesspolicy.FieldMode)
	return u
}

// SetDefaultForNewUsers sets the "default_for_new_users" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) SetDefaultForNewUsers(v bool) *OpenAIOAuthAccountAccessPolicyUpsert {
	u.Set(openaioauthaccountaccesspolicy.FieldDefaultForNewUsers, v)
	return u
}

// UpdateDefaultForNewUsers sets the "default_for_new_users" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) UpdateDefaultForNewUsers() *OpenAIOAuthAccountAccessPolicyUpsert {
	u.SetExcluded(openaioauthaccountaccesspolicy.FieldDefaultForNewUsers)
	return u
}

// SetRevision sets the "revision" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) SetRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpsert {
	u.Set(openaioauthaccountaccesspolicy.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) UpdateRevision() *OpenAIOAuthAccountAccessPolicyUpsert {
	u.SetExcluded(openaioauthaccountaccesspolicy.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) AddRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpsert {
	u.Add(openaioauthaccountaccesspolicy.FieldRevision, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) SetUpdatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyUpsert {
	u.Set(openaioauthaccountaccesspolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsert) UpdateUpdatedAt() *OpenAIOAuthAccountAccessPolicyUpsert {
	u.SetExcluded(openaioauthaccountaccesspolicy.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) UpdateNewValues() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(openaioauthaccountaccesspolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) Ignore() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) DoNothing() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthAccountAccessPolicyCreate.OnConflict
// documentation for more info.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) Update(set func(*OpenAIOAuthAccountAccessPolicyUpsert)) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthAccountAccessPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) SetAccountID(v int64) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) UpdateAccountID() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateAccountID()
	})
}

// SetMode sets the "mode" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) SetMode(v openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) UpdateMode() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateMode()
	})
}

// SetDefaultForNewUsers sets the "default_for_new_users" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) SetDefaultForNewUsers(v bool) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetDefaultForNewUsers(v)
	})
}

// UpdateDefaultForNewUsers sets the "default_for_new_users" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) UpdateDefaultForNewUsers() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateDefaultForNewUsers()
	})
}

// SetRevision sets the "revision" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) SetRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) AddRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) UpdateRevision() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) SetUpdatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) UpdateUpdatedAt() *OpenAIOAuthAccountAccessPolicyUpsertOne {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthAccountAccessPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OpenAIOAuthAccountAccessPolicyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OpenAIOAuthAccountAccessPolicyCreateBulk is the builder for creating many OpenAIOAuthAccountAccessPolicy entities in bulk.
type OpenAIOAuthAccountAccessPolicyCreateBulk struct {
	config
	err      error
	builders []*OpenAIOAuthAccountAccessPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the OpenAIOAuthAccountAccessPolicy entities in the database.
func (_c *OpenAIOAuthAccountAccessPolicyCreateBulk) Save(ctx context.Context) ([]*OpenAIOAuthAccountAccessPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OpenAIOAuthAccountAccessPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpenAIOAuthAccountAccessPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OpenAIOAuthAccountAccessPolicyCreateBulk) SaveX(ctx context.Context) []*OpenAIOAuthAccountAccessPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OpenAIOAuthAccountAccessPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OpenAIOAuthAccountAccessPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OpenAIOAuthAccountAccessPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OpenAIOAuthAccountAccessPolicyUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *OpenAIOAuthAccountAccessPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	_c.conflict = opts
	return &OpenAIOAuthAccountAccessPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OpenAIOAuthAccountAccessPolicyCreateBulk) OnConflictColumns(columns ...string) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OpenAIOAuthAccountAccessPolicyUpsertBulk{
		create: _c,
	}
}

// OpenAIOAuthAccountAccessPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of OpenAIOAuthAccountAccessPolicy nodes.
type OpenAIOAuthAccountAccessPolicyUpsertBulk struct {
	create *OpenAIOAuthAccountAccessPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) UpdateNewValues() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(openaioauthaccountaccesspolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OpenAIOAuthAccountAccessPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) Ignore() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) DoNothing() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OpenAIOAuthAccountAccessPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) Update(set func(*OpenAIOAuthAccountAccessPolicyUpsert)) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OpenAIOAuthAccountAccessPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) SetAccountID(v int64) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) UpdateAccountID() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateAccountID()
	})
}

// SetMode sets the "mode" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) SetMode(v openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) UpdateMode() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateMode()
	})
}

// SetDefaultForNewUsers sets the "default_for_new_users" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) SetDefaultForNewUsers(v bool) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetDefaultForNewUsers(v)
	})
}

// UpdateDefaultForNewUsers sets the "default_for_new_users" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) UpdateDefaultForNewUsers() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateDefaultForNewUsers()
	})
}

// SetRevision sets the "revision" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) SetRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) AddRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) UpdateRevision() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) SetUpdatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) UpdateUpdatedAt() *OpenAIOAuthAccountAccessPolicyUpsertBulk {
	return u.Update(func(s *OpenAIOAuthAccountAccessPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OpenAIOAuthAccountAccessPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OpenAIOAuthAccountAccessPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OpenAIOAuthAccountAccessPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
