// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/account"
	"github.com/LuckyKuang/sub2api-plus/ent/openaioauthaccountaccesspolicy"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// OpenAIOAuthAccountAccessPolicyUpdate is the builder for updating OpenAIOAuthAccountAccessPolicy entities.
type OpenAIOAuthAccountAccessPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthAccountAccessPolicyMutation
}

// Where appends a list predicates to the OpenAIOAuthAccountAccessPolicyUpdate builder.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) Where(ps ...predicate.OpenAIOAuthAccountAccessPolicy) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetAccountID(v int64) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetNillableAccountID(v *int64) *OpenAIOAuthAccountAccessPolicyUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetMode(v openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetNillableMode(v *openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetDefaultForNewUsers sets the "default_for_new_users" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetDefaultForNewUsers(v bool) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.SetDefaultForNewUsers(v)
	return _u
}

// SetNillableDefaultForNewUsers sets the "default_for_new_users" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetNillableDefaultForNewUsers(v *bool) *OpenAIOAuthAccountAccessPolicyUpdate {
	if v != nil {
		_u.SetDefaultForNewUsers(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetNillableRevision(v *int64) *OpenAIOAuthAccountAccessPolicyUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) AddRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetUpdatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SetAccount(v *Account) *OpenAIOAuthAccountAccessPolicyUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the OpenAIOAuthAccountAccessPolicyMutation object of the builder.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) Mutation() *OpenAIOAuthAccountAccessPolicyMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) ClearAccount() *OpenAIOAuthAccountAccessPolicyUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthaccountaccesspolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthAccountAccessPolicyUpdate) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := openaioauthaccountaccesspolicy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthAccountAccessPolicy.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := openaioauthaccountaccesspolicy.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthAccountAccessPolicy.revision": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIOAuthAccountAccessPolicy.account"`)
	}
	return nil
}

func (_u *OpenAIOAuthAccountAccessPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthaccountaccesspolicy.Table, openaioauthaccountaccesspolicy.Columns, sqlgraph.NewFieldSpec(openaioauthaccountaccesspolicy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DefaultForNewUsers(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldDefaultForNewUsers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(openaioauthaccountaccesspolicy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   openaioauthaccountaccesspolicy.AccountTable,
			Columns: []string{openaioauthaccountaccesspolicy.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   openaioauthaccountaccesspolicy.AccountTable,
			Columns: []string{openaioauthaccountaccesspolicy.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthaccountaccesspolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIOAuthAccountAccessPolicyUpdateOne is the builder for updating a single OpenAIOAuthAccountAccessPolicy entity.
type OpenAIOAuthAccountAccessPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIOAuthAccountAccessPolicyMutation
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetAccountID(v int64) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetNillableAccountID(v *int64) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetMode(v openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetNillableMode(v *openaioauthaccountaccesspolicy.Mode) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetDefaultForNewUsers sets the "default_for_new_users" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetDefaultForNewUsers(v bool) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.SetDefaultForNewUsers(v)
	return _u
}

// SetNillableDefaultForNewUsers sets the "default_for_new_users" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetNillableDefaultForNewUsers(v *bool) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	if v != nil {
		_u.SetDefaultForNewUsers(*v)
	}
	return _u
}

// SetRevision sets the "revision" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetNillableRevision(v *int64) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) AddRevision(v int64) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetUpdatedAt(v time.Time) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SetAccount(v *Account) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the OpenAIOAuthAccountAccessPolicyMutation object of the builder.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) Mutation() *OpenAIOAuthAccountAccessPolicyMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) ClearAccount() *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the OpenAIOAuthAccountAccessPolicyUpdate builder.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) Where(ps ...predicate.OpenAIOAuthAccountAccessPolicy) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) Select(field string, fields ...string) *OpenAIOAuthAccountAccessPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIOAuthAccountAccessPolicy entity.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) Save(ctx context.Context) (*OpenAIOAuthAccountAccessPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) SaveX(ctx context.Context) *OpenAIOAuthAccountAccessPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := openaioauthaccountaccesspolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := openaioauthaccountaccesspolicy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthAccountAccessPolicy.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := openaioauthaccountaccesspolicy.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "OpenAIOAuthAccountAccessPolicy.revision": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIOAuthAccountAccessPolicy.account"`)
	}
	return nil
}

func (_u *OpenAIOAuthAccountAccessPolicyUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIOAuthAccountAccessPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthaccountaccesspolicy.Table, openaioauthaccountaccesspolicy.Columns, sqlgraph.NewFieldSpec(openaioauthaccountaccesspolicy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIOAuthAccountAccessPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaioauthaccountaccesspolicy.FieldID)
		for _, f := range fields {
			if !openaioauthaccountaccesspolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaioauthaccountaccesspolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DefaultForNewUsers(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldDefaultForNewUsers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(openaioauthaccountaccesspolicy.FieldRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(openaioauthaccountaccesspolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   openaioauthaccountaccesspolicy.AccountTable,
			Columns: []string{openaioauthaccountaccesspolicy.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   openaioauthaccountaccesspolicy.AccountTable,
			Columns: []string{openaioauthaccountaccesspolicy.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OpenAIOAuthAccountAccessPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthaccountaccesspolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
