// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/openaioauthaccountusergrant"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// OpenAIOAuthAccountUserGrantDelete is the builder for deleting a OpenAIOAuthAccountUserGrant entity.
type OpenAIOAuthAccountUserGrantDelete struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthAccountUserGrantMutation
}

// Where appends a list predicates to the OpenAIOAuthAccountUserGrantDelete builder.
func (_d *OpenAIOAuthAccountUserGrantDelete) Where(ps ...predicate.OpenAIOAuthAccountUserGrant) *OpenAIOAuthAccountUserGrantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OpenAIOAuthAccountUserGrantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIOAuthAccountUserGrantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OpenAIOAuthAccountUserGrantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(openaioauthaccountusergrant.Table, sqlgraph.NewFieldSpec(openaioauthaccountusergrant.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OpenAIOAuthAccountUserGrantDeleteOne is the builder for deleting a single OpenAIOAuthAccountUserGrant entity.
type OpenAIOAuthAccountUserGrantDeleteOne struct {
	_d *OpenAIOAuthAccountUserGrantDelete
}

// Where appends a list predicates to the OpenAIOAuthAccountUserGrantDelete builder.
func (_d *OpenAIOAuthAccountUserGrantDeleteOne) Where(ps ...predicate.OpenAIOAuthAccountUserGrant) *OpenAIOAuthAccountUserGrantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OpenAIOAuthAccountUserGrantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{openaioauthaccountusergrant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OpenAIOAuthAccountUserGrantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
