// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuckyKuang/sub2api-plus/ent/account"
	"github.com/LuckyKuang/sub2api-plus/ent/openaioauthaccountaccesspolicy"
)

// OpenAIOAuthAccountAccessPolicy is the model entity for the OpenAIOAuthAccountAccessPolicy schema.
type OpenAIOAuthAccountAccessPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode openaioauthaccountaccesspolicy.Mode `json:"mode,omitempty"`
	// DefaultForNewUsers holds the value of the "default_for_new_users" field.
	DefaultForNewUsers bool `json:"default_for_new_users,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int64 `json:"revision,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OpenAIOAuthAccountAccessPolicyQuery when eager-loading is set.
	Edges        OpenAIOAuthAccountAccessPolicyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OpenAIOAuthAccountAccessPolicyEdges holds the relations/edges for other nodes in the graph.
type OpenAIOAuthAccountAccessPolicyEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OpenAIOAuthAccountAccessPolicyEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpenAIOAuthAccountAccessPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case openaioauthaccountaccesspolicy.FieldDefaultForNewUsers:
			values[i] = new(sql.NullBool)
		case openaioauthaccountaccesspolicy.FieldID, openaioauthaccountaccesspolicy.FieldAccountID, openaioauthaccountaccesspolicy.FieldRevision:
			values[i] = new(sql.NullInt64)
		case openaioauthaccountaccesspolicy.FieldMode:
			values[i] = new(sql.NullString)
		case openaioauthaccountaccesspolicy.FieldCreatedAt, openaioauthaccountaccesspolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpenAIOAuthAccountAccessPolicy fields.
func (_m *OpenAIOAuthAccountAccessPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case openaioauthaccountaccesspolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case openaioauthaccountaccesspolicy.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case openaioauthaccountaccesspolicy.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = openaioauthaccountaccesspolicy.Mode(value.String)
			}
		case openaioauthaccountaccesspolicy.FieldDefaultForNewUsers:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field default_for_new_users", values[i])
			} else if value.Valid {
				_m.DefaultForNewUsers = value.Bool
			}
		case openaioauthaccountaccesspolicy.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case openaioauthaccountaccesspolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case openaioauthaccountaccesspolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpenAIOAuthAccountAccessPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *OpenAIOAuthAccountAccessPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the OpenAIOAuthAccountAccessPolicy entity.
func (_m *OpenAIOAuthAccountAccessPolicy) QueryAccount() *AccountQuery {
	return NewOpenAIOAuthAccountAccessPolicyClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this OpenAIOAuthAccountAccessPolicy.
// Note that you need to call OpenAIOAuthAccountAccessPolicy.Unwrap() before calling this method if this OpenAIOAuthAccountAccessPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OpenAIOAuthAccountAccessPolicy) Update() *OpenAIOAuthAccountAccessPolicyUpdateOne {
	return NewOpenAIOAuthAccountAccessPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OpenAIOAuthAccountAccessPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OpenAIOAuthAccountAccessPolicy) Unwrap() *OpenAIOAuthAccountAccessPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpenAIOAuthAccountAccessPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OpenAIOAuthAccountAccessPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("OpenAIOAuthAccountAccessPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	builder.WriteString("default_for_new_users=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultForNewUsers))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpenAIOAuthAccountAccessPolicies is a parsable slice of OpenAIOAuthAccountAccessPolicy.
type OpenAIOAuthAccountAccessPolicies []*OpenAIOAuthAccountAccessPolicy
