// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/account"
	"github.com/LuckyKuang/sub2api-plus/ent/openaioauthaccountusergrant"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
	"github.com/LuckyKuang/sub2api-plus/ent/user"
)

// OpenAIOAuthAccountUserGrantUpdate is the builder for updating OpenAIOAuthAccountUserGrant entities.
type OpenAIOAuthAccountUserGrantUpdate struct {
	config
	hooks    []Hook
	mutation *OpenAIOAuthAccountUserGrantMutation
}

// Where appends a list predicates to the OpenAIOAuthAccountUserGrantUpdate builder.
func (_u *OpenAIOAuthAccountUserGrantUpdate) Where(ps ...predicate.OpenAIOAuthAccountUserGrant) *OpenAIOAuthAccountUserGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SetAccountID(v int64) *OpenAIOAuthAccountUserGrantUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SetNillableAccountID(v *int64) *OpenAIOAuthAccountUserGrantUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SetUserID(v int64) *OpenAIOAuthAccountUserGrantUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SetNillableUserID(v *int64) *OpenAIOAuthAccountUserGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SetAccount(v *Account) *OpenAIOAuthAccountUserGrantUpdate {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SetUser(v *User) *OpenAIOAuthAccountUserGrantUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OpenAIOAuthAccountUserGrantMutation object of the builder.
func (_u *OpenAIOAuthAccountUserGrantUpdate) Mutation() *OpenAIOAuthAccountUserGrantMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountUserGrantUpdate) ClearAccount() *OpenAIOAuthAccountUserGrantUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OpenAIOAuthAccountUserGrantUpdate) ClearUser() *OpenAIOAuthAccountUserGrantUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OpenAIOAuthAccountUserGrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthAccountUserGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OpenAIOAuthAccountUserGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthAccountUserGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthAccountUserGrantUpdate) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIOAuthAccountUserGrant.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIOAuthAccountUserGrant.user"`)
	}
	return nil
}

func (_u *OpenAIOAuthAccountUserGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthaccountusergrant.Table, openaioauthaccountusergrant.Columns, sqlgraph.NewFieldSpec(openaioauthaccountusergrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.AccountTable,
			Columns: []string{openaioauthaccountusergrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.AccountTable,
			Columns: []string{openaioauthaccountusergrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.UserTable,
			Columns: []string{openaioauthaccountusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.UserTable,
			Columns: []string{openaioauthaccountusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthaccountusergrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OpenAIOAuthAccountUserGrantUpdateOne is the builder for updating a single OpenAIOAuthAccountUserGrant entity.
type OpenAIOAuthAccountUserGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpenAIOAuthAccountUserGrantMutation
}

// SetAccountID sets the "account_id" field.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SetAccountID(v int64) *OpenAIOAuthAccountUserGrantUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SetNillableAccountID(v *int64) *OpenAIOAuthAccountUserGrantUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SetUserID(v int64) *OpenAIOAuthAccountUserGrantUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SetNillableUserID(v *int64) *OpenAIOAuthAccountUserGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SetAccount(v *Account) *OpenAIOAuthAccountUserGrantUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SetUser(v *User) *OpenAIOAuthAccountUserGrantUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OpenAIOAuthAccountUserGrantMutation object of the builder.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) Mutation() *OpenAIOAuthAccountUserGrantMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) ClearAccount() *OpenAIOAuthAccountUserGrantUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) ClearUser() *OpenAIOAuthAccountUserGrantUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OpenAIOAuthAccountUserGrantUpdate builder.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) Where(ps ...predicate.OpenAIOAuthAccountUserGrant) *OpenAIOAuthAccountUserGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) Select(field string, fields ...string) *OpenAIOAuthAccountUserGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OpenAIOAuthAccountUserGrant entity.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) Save(ctx context.Context) (*OpenAIOAuthAccountUserGrant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) SaveX(ctx context.Context) *OpenAIOAuthAccountUserGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OpenAIOAuthAccountUserGrantUpdateOne) check() error {
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIOAuthAccountUserGrant.account"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OpenAIOAuthAccountUserGrant.user"`)
	}
	return nil
}

func (_u *OpenAIOAuthAccountUserGrantUpdateOne) sqlSave(ctx context.Context) (_node *OpenAIOAuthAccountUserGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(openaioauthaccountusergrant.Table, openaioauthaccountusergrant.Columns, sqlgraph.NewFieldSpec(openaioauthaccountusergrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpenAIOAuthAccountUserGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, openaioauthaccountusergrant.FieldID)
		for _, f := range fields {
			if !openaioauthaccountusergrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != openaioauthaccountusergrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.AccountTable,
			Columns: []string{openaioauthaccountusergrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.AccountTable,
			Columns: []string{openaioauthaccountusergrant.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.UserTable,
			Columns: []string{openaioauthaccountusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   openaioauthaccountusergrant.UserTable,
			Columns: []string{openaioauthaccountusergrant.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OpenAIOAuthAccountUserGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{openaioauthaccountusergrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
