// Code generated by ent, DO NOT EDIT.

package openaioauthaccountusergrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldAccountID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldUserID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNotIn(FieldAccountID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpenAIOAuthAccountUserGrant) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpenAIOAuthAccountUserGrant) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpenAIOAuthAccountUserGrant) predicate.OpenAIOAuthAccountUserGrant {
	return predicate.OpenAIOAuthAccountUserGrant(sql.NotPredicates(p))
}
